### ISSUE TITLE
Hello, I'm stacked with sending file to mongodb stitch as binary from android

### ISSUE THREAD

**Issue by scooltr** [mongodb/stitch-android-sdk#117]
Can you please help me with that? I'm trying to send the image files

                                              ```
  final Document doc = new Document("owner_id", task.getResult
                                                        ().getId());
//here I was trying to send the file but it was unsuccessful
                                                    for (int p = 0; p < collectedImagesForSend.size(); p++) {
                                                        File imgFile = new File(collectedImagesForSend.get(p));
                                                        doc.put("patrolImgFile",imgFile);
                                                    }
                                                }
                                                return coll.insertOne(doc);
                                            }
```

**Comment by dkaminsky** [comment]
Thanks for reaching out!

I think the confusion here is that there is no “natural” way for our API to decide how to serialize your File. In order to put your data into a document you will need to open your file locally and read the data into an object type that the default codec can understand (eg a byte array for a binary blob).

See if that helps and let us know!

**Comment by dkaminsky** [comment]
Another important thing to know here is that documents can not exceed 16mb, so if your images are larger than that for any reason you will need to compress them before they can be inserted.

**Comment by scooltr** [comment]
> Thanks for reaching out! I think the confusion here is that there is no “natural” way for our API to decide how to serialize your File. In order to put your data into a document you will need to open your file locally and read the data into an object type that the default codec can understand (eg a byte array for a binary blob). See if that helps and let us know!
> […](#)
> On Mar 18, 2019, at 11:53 AM, scooltr ***@***.***> wrote: Can you please help me with that? I'm trying to send the image files final Document doc = new Document("owner_id", task.getResult ().getId()); //here I was trying to send the file but it was unsuccessful for (int p = 0; p < collectedImagesForSend.size(); p++) { File imgFile = new File(collectedImagesForSend.get(p)); doc.put("patrolImgFile",imgFile); } } return coll.insertOne(doc); } — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you, it was helpful))

**Comment by dkaminsky** [comment]
Great! I'm glad you've got it worked out. I'm going to close out this issue for now, then. Please feel free to open another if you find something that doesn't work or to reach out on our Google groups or community slack channel.
