### ISSUE TITLE
 How do I login by function

### ISSUE THREAD

**Issue by eslam2010011** [mongodb/stitch-android-sdk#129]
I am sorry because I say many questions   

 How do I login by function

I want an illustrative example

Thank you

**Comment by tkaye407** [comment]
Hi, can you please explain what it is you are trying to do? What authentication provider are you trying to use? Also, are you trying to log in a user from a Stitch-console function? If so, what is your use case for this as opposed to using the SDK authentication methods?

**Comment by eslam2010011** [comment]
I try to log in via webhooks  but how do I register by  webhooks  what code to type in webhooks thanks

**Comment by eslam2010011** [comment]
I do not want to use SDK in the registry but I want to register via webhooks and I will tell the request via okhttp3 but what code do i write in webhooks to login to login

**Comment by drewdipalma** [comment]
Hi – I think what you would like to use is the ["Run As" functionality of webhooks](https://docs.mongodb.com/stitch/services/create-a-service-webhook/index.html#select-a-user-to-execute-the-webhook).  This will allow you to run a code when a request is made which will then decide the permissions for the following function execution.

**Comment by tkaye407** [comment]
I hope the above solution accomplished what you needed. I will close this issue, but please feel free to reach out with any other questions or concerns.
