### ISSUE TITLE
Getting java.lang.NullPointerException by this.splitToken(jwt)

### ISSUE THREAD

**Issue by dfilipic** [mongodb/stitch-android-sdk#18]
Hello,

I have updated SDK from 0.1.0-SNAPSHOT to 2.1.1.

and now it throws "java.lang.NullPointerException" by insertOne. This exception fires because _accessToken = null in AuthInfo. This happens in DecodedJWT this.splitToken(jwt).

My Authenticate code looks like this:
_stitchClient.logInWithProvider(new AnonymousAuthProvider()).addOnCompleteListener(new OnCompleteListener<String>() {
                        @Override
                        public void onComplete(@NonNull final Task<String> task) {
                            if (task.isSuccessful()) {
                                Log.d("stitch", "logged in anonymously as user " + task.getResult());
                            } else {
                                Log.e("stitch", "failed to log in anonymously", task.getException());
                            }
                        }
                    });
- Min Sdk Version API 19
- Target Sdk API 27

**Comment by edaniels** [comment]
@jsflax, could you take a look at this?

**Comment by edaniels** [comment]
Hey @dfilipic,

I'm pretty sure what happened here was a poor migration path on our part. That older version of the SDK (0.x) stored auth information in a different way than what 2.x expects. If you're testing an application, you can reinstall the app to clear the shared preferences. It's likely that you have old auth information lying around. If that does not work for you, let me know. Sorry about that! If we ever make a on disk format change like that again, we will provide a better (not broken) migration path.

-Eric

**Comment by dfilipic** [comment]
Hey @edaniels,

thank you for your fast answer.
I solved the Issue without reinstall.

Solution is to set android:allowBackup="false"
tools:replace="android:allowBackup"
in AndroidManifest.xml. My app do not need backups.
