### ISSUE TITLE
com.mongodb.stitch.android.StitchException$StitchRequestException: com.android.volley.TimeoutError

### ISSUE THREAD

**Issue by dgaurav-163** [mongodb/stitch-android-sdk#29]
Hi Team

I am getting timeout error when save data in stich db. I think, it's internally call Volley for network call.

I also tried to set increased timeout in request but after it, still getting same issue.

request.setRetryPolicy(new DefaultRetryPolicy(90000, DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));

Please suggest How we can fix same issue.

**Comment by jsflax** [comment]
Hi dgaurav-163,

Do you have more information about the call you are trying to make? A code snippet would be helpful here.

Thanks!

**Comment by dgaurav-163** [comment]
Hi @jsflax : I am making stich db call simply but I am getting timeout error in response. I have already tried to change timeout but issue could not get resolve. 

 com.mongodb.stitch.android.StitchException$StitchRequestException: com.android.volley.TimeoutError
                                                                   at com.mongodb.stitch.android.StitchError.parseRequestError(StitchError.java:28)
                                                                   at com.mongodb.stitch.android.StitchClient$18.onErrorResponse(StitchClient.java:764)
                                                                   at com.android.volley.Request.deliverError(Request.java:598)

Let me know If you have any other information is required. 

Let me know also when stich db sync from central(global) db? means it will call each time?

Thanks
Gaurav

**Comment by jsflax** [comment]
It's possible that the request is simply taking too long.

Are you making a heavy query? What are the network conditions?

**Comment by edaniels** [comment]
@dgaurav-163 you can now set the global request time out when you build a `StitchAppClient` in 4.0.0-beta-1
