### ISSUE TITLE
Need to know How we add sort keys in query

### ISSUE THREAD

**Issue by dgaurav-163** [mongodb/stitch-android-sdk#31]
Hi 

Need to know how we add sort keyboard in query? I am not able to get any method or parameter by we can pass sort keys in query.

Please suggest

Thanks
Gaurav

**Comment by jsflax** [comment]
Hi dgaurav-163,

Could you provide a code sample of what you're trying to do? Thanks.

**Comment by dgaurav-163** [comment]
Hi Please find code sample 

Document query = new Document("user_id",userId);
            query.append("mode", "car");
//            Document sortParam = new Document("firstUpdateTimestamp", "-1");
//            query.append("sort", sortParam);
            _mongoClient.getDatabase(DATABASE).getCollection(COLLECTION_NAME).find(query, QUERY_LIMIT)

We have to sort data according to "firstUpdateTimestamp" field so where I can add sort key in code.

Please suggest

**Comment by edaniels** [comment]
@dgaurav-163 this is possible now as of `4.0.0-beta-1`
