### ISSUE TITLE
Kotlin sdk

### ISSUE THREAD

**Issue by xxyyzz2050** [mongodb/stitch-android-sdk#81]
would you provide a kotlin sdk for android?

**Comment by jsflax** [comment]
Hi there,

The Java SDK is interoperable with Kotlin. Are you having any issues with the interoperability?

**Comment by adamchel** [comment]
Closing this issue as it's been a while. Please let us know here or open a new issue if you have any trouble getting the Kotlin interoperability to work. Thanks!
