### ISSUE TITLE
[Help] ANR on access token expire

### ISSUE THREAD

**Issue by shahsurajk** [mongodb/stitch-android-sdk#91]
**This is not a confirmed bug, but logs point towards the same, hence the help tag**

### Pretext
* Stitch uses access-token and refresh token mechanism for it's internal authentication. 
* Android 8.0 and above introduced limits for execution of background tasks.
* Currently the application uses `AccessTokenRefresher` to refresh the token as long as the application lives with a specified interval (60 seconds). 
* The `refreshAccessToken` acquires lock on the thread when it begins. 

### When does it occur? 
* Happens mostly on devices running 8.0 (but did occur on lower end devices as well) and above when the app is in background and started after long periods of time (in hours, even though the access token expires every 30 mins and is re-requested, I tried various ways of changing the local time to force the refresh and reproduce the anr but failed to do so for a guaranteed 100% of time.)

### How is it related to Stitch and the SDK?
* I tried adding logs to every place I can, before the request is sent, after it etc, originally i was using coroutines, so i thought maybe Tasks and Coroutines don't go along much as I had to use, `Tasks.await` to make it go in a sync fashion in a coroutine with IO context (something similar to a worker thread), then i removed the entire `suspend` functionality and called vanilla task api with `onCompletionListener` in both the cases the request was sent but never replied back to when an ANR occurs. 
* Since Stitch uses Okhttp and Okio for internal network requests, it should crash if the timeout occurs, (60 seconds if using the default configuration) but the application doesn't crash either, indicating that there could be a deadlock situation and the request never went through.
* I also added StrictMode to check for VM and thread policy violations and when the ANR occurs, some policy violation for OkHttp request in the internal package are visible. ([thread_vm_policy_violations.txt](https://github.com/mongodb/stitch-android-sdk/files/2786598/thread_vm_policy_violations.txt)
[traces.txt](https://github.com/mongodb/stitch-android-sdk/files/2786601/traces.txt))

Though i'm not sure as to it's because of the sdk, i've narrowed it down to stitch, that's all. 

PS: Also it would be great if there could be a debug flag, which clients can set, where Stitch would log if not anything else, just the error stack traces, for now the sdk simple "swallows" the exceptions ([Example](https://github.com/mongodb/stitch-android-sdk/blob/master/core/sdk/src/main/java/com/mongodb/stitch/core/auth/internal/AccessTokenRefresher.java#L76))  and doesn't print stack traces, though this behaviour is good but there should be flag to set it from the client side, just a suggestion.

**Comment by jsflax** [comment]
Hi there,

Interesting find! I have a view initial thoughts, but first– in simple terms, what is the actual error you are seeing? Are you unable to make requests through Stitch? Is the application crashing?

**Comment by shahsurajk** [comment]
My bad, I use a background thread to check the remote mongo database whether the user has a particular feature enabled or not, this request is made on the first activity visible in the application lifecycle. I get an ANR and the UI is not rendered. I know this sounds very stupid as there are tonnes of SO questions on how to fix ANRs and preventing them. But this has nothing to do with blocking of threads i feel, i think there could be a deadlock. 

To answer your question in simple terms, the application doesn't crash, an ANR comes, only when opened after a long delay (sufficient enough for the access token to expire).

**Comment by jsflax** [comment]
Could you copy over some of your coroutine code? Coroutines need to be used
in a very specific way on Android. Any sample code would be helpful here.

Ar Céad 23 Ean 2019 ag 10:44, scríobh MadScientist <notifications@github.com

**Comment by shahsurajk** [comment]
I'm no longer using coroutines. Thought might be in the way i was using it. I moved on to vanilla tasks api. But the problem still persists. For brevity, i'll post both corountine and vanilla implementation. 

### Vanilla
```kotlin
Log.d("XXXManager", "checkAndLoginUserToXXX: started")

        MongoDBManager.getCurrentUserDocumentByObjectID(
                userProfile.mongodbObjectId
            ).addOnCompleteListener { userDocumentTask ->
            val userDocument = userDocumentTask.result
            
           // this is the log which never appears when there's an ANR
            Log.d("XXXManager", "checkAndLoginUserToXXX: synced from mongo")

            if (userDocumentTask.isSuccessful && userDocument!=null){
               // updating the UI etc.    
            }
       }
```
### With Coroutines
The function is marked with `suspend`
```kotlin
Log.d("XXXManager", "checkAndLoginUserToXXX: started")

        val userDocument = withContext(Dispatchers.IO){
            Tasks.await(
                    MongoDBManager.getCurrentUserDocumentByObjectID(
                            userProfile.mongodbObjectId
                    )
            )
        } ?:return

        // this one doesn't appear.
        Log.d("XXXManager", "checkAndLoginUserToXXX: synced from mongo")

      // update ui. 
      withContext(Dispatchers.Main){
            // update UI
        }
```
This is called as follows
```kotlin
        private val ioScope = CoroutineScope(Dispatchers.IO + SupervisorJob())
        ....
        ioScope.launch { 
            // suspend function called here
        }
```

#### The function block 

```kotlin
fun getCurrentUserDocumentByObjectID(objectId: String?, vararg includeProjections: String = arrayOf()): Task<Document?>{
        return MongoDBManager.getUsersCollection()
                .find(
                        eq(MongoDBCollections.MongoUserColumns._ID, ObjectId(objectId))
                )
                .apply {
                    if (includeProjections.isNotEmpty()){
                        projection(Projections.include(*includeProjections))
                    }
                }.first()
    }
```
and 
```kotlin
    fun getUsersCollection(): RemoteMongoCollection<Document> {
        return getRemoteMongoDatabase().getCollection(COLLECTION_USERS)
    }
```
also
```kotlin
private fun getRemoteMongoDatabase(): RemoteMongoDatabase {
        return Stitch.getDefaultAppClient().getServiceClient(RemoteMongoClient.factory, "service-name").getDatabase(DATABASE_NAME)
    }
```

**Comment by jsflax** [comment]
And what method in the application lifecycle are you calling this in? Are you calling `setContentView` where you should be?

**Comment by shahsurajk** [comment]
Yes, i'm calling the `setContentView` where i should be. Again, this doesn't happen on every app open. It only happens when the duration is long (an hour or 2 maybe). But if you leave the entire flow of UI threads etc, the callback should come inside the `onCompleteListener`, but it doesn't, only when an ANR occurs, suggesting that the response was never completed and it doesn't even throw a timeout exception, thus maybe something like a deadlock  might be occuring as the token request might also be in progress.

**Comment by jsflax** [comment]
Can you send the log messages when this occurs?

**Comment by shahsurajk** [comment]
@jsflax update: The problem was in the way i was using coroutines. I was using [Tasks.await](https://developers.google.com/android/reference/com/google/android/gms/tasks/Tasks#await(com.google.android.gms.tasks.Task%3CTResult%3E)) which is a blocking call inside `withContext` which again blocks the current thread. Even though i'm using `withContext(Dispatchers.IO)` i do not understand why it blocks my main thread. but using the vanilla tasks api and testing extensively with considerable long periodic wait times, i can confirm, it had nothing to do with the SDK. thank you so much for your time. muchas gracias!

**Comment by shahsurajk** [comment]
Update 2: found the real culprit. We had a function block for checking play services availability, this i assume like the old FCM token api hangs up if play services is busy. Sorry to have bothered you with my stupid theories about deadlock etc. Thank you for your time once again. I can finally sleep in peace!
